### ISSUE TITLE
ldap module no longer present

### ISSUE THREAD

**Issue by travisghansen** [AVENTER-UG/docker-matrix#21]
It appears to be since `0.34.1.1` as I reverted back to `v0.34.0` and all is well.
```
No handlers could be found for logger "synapse.config.server"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 576, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 571, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 312, in setup
    config_options,
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 356, in load_or_generate_config
    generate_keys=generate_keys,
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 402, in read_config_files
    self.invoke_all("read_config", config)
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 146, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/password_auth_providers.py", line 48, in read_config
    "config": provider['config'],
  File "/usr/local/lib/python2.7/dist-packages/synapse/util/module_loader.py", line 32, in load_module
    module = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ldap_auth_provider
```

**Comment by andreaspeters** [comment]
Hi @travisghansen , thanks for your issue. Can u send me your homeserver.yaml therefore I can have a look?

**Comment by mvgorcum** [comment]
I don't currently have time to verify, but it's possible that PR #20 can solve this issue.

**Comment by andreaspeters** [comment]
Ok, then let us try. I will merge and rebuild version v0.34.1.1 this night.

**Comment by travisghansen** [comment]
Sorry, been a bit busy.  It's a pretty standard file, here is the relevant bits:
```
password_providers:
    - module: "ldap_auth_provider.LdapAuthProvider"
      config:
        enabled: true
        uri: "ldap://ldap:389"
        start_tls: false
        base: "ou=People,dc=acme,dc=co"
        attributes:
           uid: "uid"
           mail: "mail"
           name: "cn"
        bind_dn: "cn=default,ou=Services,dc=acme,dc=co"
        bind_password: "secret"
        filter: "(objectClass=inetOrgPerson) (memberOf=cn=matrix,ou=Groups,dc=acme,dc=co)"
```

**Comment by travisghansen** [comment]
Any progress on this?  Should I attempt again?

**Comment by andreaspeters** [comment]
Hi @travisghansen, sorry, yes please try again. I already merged @mvgorcum PR. If its not working, then give me time over weekend. Very busy at the moment. :-(

**Comment by travisghansen** [comment]
Updated to `latest` (`0.34.1.1`) and things seem back in order.  Thanks!
