### ISSUE TITLE
v0.34.1.1 missing bleach module

### ISSUE THREAD

**Issue by nightah** [AVENTER-UG/docker-matrix#23]
It looks like the `latest` version also breaks if you have email configuration setup with the following error:
```
-=> start turn
The riot web client is now handled via silvio/matrix-riot-docker
-=> start matrix
2019-01-14 09:15:50,878 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-01-14 09:15:50,879 INFO Included extra file "/conf/supervisord-matrix.conf" during parsing
2019-01-14 09:15:50,879 INFO Included extra file "/conf/supervisord-turnserver.conf" during parsing
2019-01-14 09:15:50,898 INFO supervisord started with pid 1
2019-01-14 09:15:51,610 INFO spawned: 'matrix' with pid 22
2019-01-14 09:15:51,622 INFO spawned: 'turnserver' with pid 23
2019-01-14 09:15:51,623 INFO reaped unknown pid 17
2019-01-14 09:15:52,625 INFO success: matrix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-14 09:15:52,632 INFO success: turnserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 576, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 571, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 312, in setup
    config_options,
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 356, in load_or_generate_config
    generate_keys=generate_keys,
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 402, in read_config_files
    self.invoke_all("read_config", config)
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 146, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/emailconfig.py", line 40, in read_config
    import bleach
ImportError: No module named bleach
2019-01-14 09:15:55,935 INFO exited: matrix (exit status 1; not expected)
```

If I roll back to `v0.34.0` everything launches correctly.

**Comment by andreaspeters** [comment]
hi @nightah,  can u try the v0.34.1.1 tagged docker image please? if its still not working, can u show me the email template part of your homeserver.yaml?

**Comment by nightah** [comment]
Hi @andreaspeters, I can confirm `v0.34.1.1` does not work, this was tagged as latest at the time of my post and I have just re-tested.

Same error as above and the following is the email template section of my homeserver.yaml:
```
email:
   enable_notifs: true
   smtp_host: "mail.example.com"
   smtp_port: 587
   smtp_user: "REDACTED"
   smtp_pass: "REDACTED"
   require_transport_security: true
   notif_from: "%(app)s Notifications <riot@example.com>"
   app_name: Matrix
   template_dir: /data/res/templates
   notif_template_html: notif_mail.html
   notif_template_text: notif_mail.txt
   notif_for_new_users: true
   riot_base_url: "https://chat.example.com"
```

**Comment by andreaspeters** [comment]
thanks @nightah  for your confirm. I will add the bleach module and push the update into the latest image. please give me feedback if its working or not.

**Comment by andreaspeters** [comment]
hi @nightah, could u already test it?

**Comment by nightah** [comment]
@andreaspeters, the `latest` tag works now with my existing configuration.
